-- 002: Staff SBA/MEQ tests, departments, committee workflow, sub_admin role
-- Run after initial schema. Safe to re-run: uses IF NOT EXISTS / exception handling where needed.

-- -----------------------------------------------------------------------------
-- Extend user role (PostgreSQL: add enum value; ignore if exists)
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_enum e
    join pg_type t on e.enumtypid = t.oid
    where t.typname = 'user_role' and e.enumlabel = 'sub_admin'
  ) then
    alter type public.user_role add value 'sub_admin';
  end if;
end
$$;

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'test_review_status') then
    create type public.test_review_status as enum (
      'pending_committee',
      'approved',
      'rejected'
    );
  end if;
end
$$;

-- -----------------------------------------------------------------------------
-- Departments (choose which department the test is for)
-- -----------------------------------------------------------------------------
create table if not exists public.departments (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  updated_at timestamptz not null default now()
);

create table if not exists public.committees (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  subject text,
  test_year int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists committees_subject_idx on public.committees (subject);
create index if not exists committees_year_idx on public.committees (test_year);

create table if not exists public.committee_members (
  committee_id uuid not null references public.committees (id) on delete cascade,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  primary key (committee_id, profile_id)
);

-- -----------------------------------------------------------------------------
-- SBA test (parent) + questions (UUID PK per question, generated by Supabase)
-- -----------------------------------------------------------------------------
create table if not exists public.sba_tests (
  id uuid primary key default gen_random_uuid(),
  subject text not null,
  subject_code text not null,
  department_id uuid references public.departments (id) on delete set null,
  committee_id uuid references public.committees (id) on delete set null,
  review_status public.test_review_status not null default 'pending_committee',
  test_year int not null default (extract(year from now())::int),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sba_tests_subject_idx on public.sba_tests (subject);
create index if not exists sba_tests_year_idx on public.sba_tests (test_year);
create index if not exists sba_tests_created_by_idx on public.sba_tests (created_by);
create index if not exists sba_tests_review_idx on public.sba_tests (review_status);

-- options: jsonb e.g. [{"id":"A","text":"..."},...]; correct_option_id matches one id
create table if not exists public.sba_test_questions (
  id uuid primary key default gen_random_uuid(),
  sba_test_id uuid not null references public.sba_tests (id) on delete cascade,
  sequence_order int not null check (sequence_order >= 1),
  stem text not null,
  image_url text,
  options jsonb not null default '[]'::jsonb,
  correct_option_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sba_test_questions_order_unique unique (sba_test_id, sequence_order)
);

create index if not exists sba_test_questions_test_idx on public.sba_test_questions (sba_test_id);

-- -----------------------------------------------------------------------------
-- MEQ test + stages (per-stage time limit and question; student types answers in app)
-- -----------------------------------------------------------------------------
create table if not exists public.meq_tests (
  id uuid primary key default gen_random_uuid(),
  subject text not null,
  subject_code text not null,
  department_id uuid references public.departments (id) on delete set null,
  committee_id uuid references public.committees (id) on delete set null,
  review_status public.test_review_status not null default 'pending_committee',
  test_year int not null default (extract(year from now())::int),
  time_limit_minutes int,
  first_page_stem text not null default '',
  vignette text not null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists meq_tests_subject_idx on public.meq_tests (subject);
create index if not exists meq_tests_year_idx on public.meq_tests (test_year);
create index if not exists meq_tests_created_by_idx on public.meq_tests (created_by);

create table if not exists public.meq_test_stages (
  id uuid primary key default gen_random_uuid(),
  meq_test_id uuid not null references public.meq_tests (id) on delete cascade,
  sequence_order int not null check (sequence_order >= 1),
  time_limit_minutes int,
  question_text text not null,
  media_urls text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint meq_test_stages_order_unique unique (meq_test_id, sequence_order)
);

create index if not exists meq_test_stages_test_idx on public.meq_test_stages (meq_test_id);

alter table if exists public.departments
  add column if not exists updated_at timestamptz not null default now();

-- Triggers: updated_at
drop trigger if exists departments_set_updated_at on public.departments;
create trigger departments_set_updated_at
  before update on public.departments
  for each row execute function public.set_updated_at();

drop trigger if exists committees_set_updated_at on public.committees;
create trigger committees_set_updated_at
  before update on public.committees
  for each row execute function public.set_updated_at();

drop trigger if exists sba_tests_set_updated_at on public.sba_tests;
create trigger sba_tests_set_updated_at
  before update on public.sba_tests
  for each row execute function public.set_updated_at();

drop trigger if exists sba_test_questions_set_updated_at on public.sba_test_questions;
create trigger sba_test_questions_set_updated_at
  before update on public.sba_test_questions
  for each row execute function public.set_updated_at();

drop trigger if exists meq_tests_set_updated_at on public.meq_tests;
create trigger meq_tests_set_updated_at
  before update on public.meq_tests
  for each row execute function public.set_updated_at();

drop trigger if exists meq_test_stages_set_updated_at on public.meq_test_stages;
create trigger meq_test_stages_set_updated_at
  before update on public.meq_test_stages
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Seed default departments (idempotent)
-- -----------------------------------------------------------------------------
insert into public.departments (name) values
  ('Internal Medicine'),
  ('Surgery'),
  ('Pediatrics'),
  ('OBGYN'),
  ('Emergency Medicine'),
  ('Anesthesiology'),
  ('Orthopedics'),
  ('ENT'),
  ('Ophthalmology'),
  ('Forensic Medicine'),
  ('Family & Community Medicine'),
  ('ICU / Critical Care'),
  ('Pathology / Lab'),
  ('Other')
on conflict (name) do nothing;

-- -----------------------------------------------------------------------------
-- handle_new_user: support sub_admin in metadata
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    case
      when new.raw_user_meta_data ->> 'role' in ('student', 'educator', 'admin', 'sub_admin')
      then (new.raw_user_meta_data ->> 'role')::public.user_role
      else 'student'::public.user_role
    end
  );
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
alter table public.departments enable row level security;
alter table public.committees enable row level security;
alter table public.committee_members enable row level security;
alter table public.sba_tests enable row level security;
alter table public.sba_test_questions enable row level security;
alter table public.meq_tests enable row level security;
alter table public.meq_test_stages enable row level security;

-- helper: is staff
-- Departments: readable by authenticated
drop policy if exists "departments_select_all" on public.departments;
create policy "departments_select_all"
  on public.departments for select
  using (auth.role() = 'authenticated');

drop policy if exists "departments_write_admin" on public.departments;
create policy "departments_write_admin"
  on public.departments for all
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- SBA tests: read own; admin all; sub_admin in subject/year scope
drop policy if exists "sba_tests_select" on public.sba_tests;
create policy "sba_tests_select"
  on public.sba_tests for select
  using (
    created_by = auth.uid()
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
    or (
      exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'sub_admin')
      and (
        exists (
          select 1
          from public.committee_members cm
          join public.committees c on c.id = cm.committee_id
          where cm.profile_id = auth.uid()
            and (c.subject is null or c.subject = sba_tests.subject)
            and (c.test_year is null or c.test_year = sba_tests.test_year)
        )
      )
    )
  );

drop policy if exists "sba_tests_insert" on public.sba_tests;
create policy "sba_tests_insert"
  on public.sba_tests for insert
  with check (
    created_by = auth.uid()
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('educator', 'admin', 'sub_admin')
    )
  );

drop policy if exists "sba_tests_update" on public.sba_tests;
create policy "sba_tests_update"
  on public.sba_tests for update
  using (
    (created_by = auth.uid() and exists (
      select 1 from public.profiles p where p.id = auth.uid() and p.role in ('educator', 'admin', 'sub_admin')
    ))
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
    or (
      exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'sub_admin')
      and (
        exists (
          select 1
          from public.committee_members cm
          where cm.committee_id = sba_tests.committee_id
            and cm.profile_id = auth.uid()
        )
      )
    )
  );

-- SBA questions: visibility mirrors parent sba_tests row
drop policy if exists "sba_test_questions_all" on public.sba_test_questions;
drop policy if exists "sba_test_questions_select" on public.sba_test_questions;
drop policy if exists "sba_test_questions_write" on public.sba_test_questions;
create policy "sba_test_questions_select"
  on public.sba_test_questions for select
  using (
    exists (
      select 1 from public.sba_tests t
      where t.id = sba_test_questions.sba_test_id
        and (
          t.created_by = auth.uid()
          or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
          or (
            exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'sub_admin')
            and exists (
              select 1
              from public.committee_members cm
              join public.committees c on c.id = cm.committee_id
              where cm.profile_id = auth.uid()
                and (c.subject is null or c.subject = t.subject)
                and (c.test_year is null or c.test_year = t.test_year)
            )
          )
        )
    )
  );

create policy "sba_test_questions_write"
  on public.sba_test_questions for all
  using (
    exists (
      select 1 from public.sba_tests t
      where t.id = sba_test_questions.sba_test_id
        and (
          t.created_by = auth.uid()
          or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        )
    )
  )
  with check (
    exists (
      select 1 from public.sba_tests t
      where t.id = sba_test_questions.sba_test_id
        and (
          t.created_by = auth.uid()
          or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        )
    )
  );

-- MEQ: same pattern
drop policy if exists "meq_tests_select" on public.meq_tests;
create policy "meq_tests_select"
  on public.meq_tests for select
  using (
    created_by = auth.uid()
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
    or (
      exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'sub_admin')
      and (
        exists (
          select 1
          from public.committee_members cm
          join public.committees c on c.id = cm.committee_id
          where cm.profile_id = auth.uid()
            and (c.subject is null or c.subject = meq_tests.subject)
            and (c.test_year is null or c.test_year = meq_tests.test_year)
        )
      )
    )
  );

drop policy if exists "meq_tests_insert" on public.meq_tests;
create policy "meq_tests_insert"
  on public.meq_tests for insert
  with check (
    created_by = auth.uid()
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('educator', 'admin', 'sub_admin')
    )
  );

drop policy if exists "meq_tests_update" on public.meq_tests;
create policy "meq_tests_update"
  on public.meq_tests for update
  using (
    (created_by = auth.uid() and exists (
      select 1 from public.profiles p where p.id = auth.uid() and p.role in ('educator', 'admin', 'sub_admin')
    ))
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
    or (
      exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'sub_admin')
      and (
        exists (
          select 1
          from public.committee_members cm
          where cm.committee_id = meq_tests.committee_id
            and cm.profile_id = auth.uid()
        )
      )
    )
  );

drop policy if exists "meq_test_stages_all" on public.meq_test_stages;
drop policy if exists "meq_test_stages_select" on public.meq_test_stages;
drop policy if exists "meq_test_stages_write" on public.meq_test_stages;
create policy "meq_test_stages_select"
  on public.meq_test_stages for select
  using (
    exists (
      select 1 from public.meq_tests t
      where t.id = meq_test_stages.meq_test_id
        and (
          t.created_by = auth.uid()
          or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
          or (
            exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'sub_admin')
            and exists (
              select 1
              from public.committee_members cm
              join public.committees c on c.id = cm.committee_id
              where cm.profile_id = auth.uid()
                and (c.subject is null or c.subject = t.subject)
                and (c.test_year is null or c.test_year = t.test_year)
            )
          )
        )
    )
  );

create policy "meq_test_stages_write"
  on public.meq_test_stages for all
  using (
    exists (
      select 1 from public.meq_tests t
      where t.id = meq_test_stages.meq_test_id
        and (
          t.created_by = auth.uid()
          or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        )
    )
  )
  with check (
    exists (
      select 1 from public.meq_tests t
      where t.id = meq_test_stages.meq_test_id
        and (
          t.created_by = auth.uid()
          or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        )
    )
  );

-- Committees: sub_admin + admin
drop policy if exists "committees_select" on public.committees;
create policy "committees_select"
  on public.committees for select
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'sub_admin'))
  );

drop policy if exists "committees_write_sub_admin" on public.committees;
create policy "committees_write_sub_admin"
  on public.committees for all
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'sub_admin'))
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'sub_admin'))
  );

drop policy if exists "committee_members_all" on public.committee_members;
drop policy if exists "committee_members_select" on public.committee_members;
drop policy if exists "committee_members_write" on public.committee_members;
create policy "committee_members_select"
  on public.committee_members for select
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'sub_admin'))
  );

create policy "committee_members_write"
  on public.committee_members for all
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'sub_admin'))
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'sub_admin'))
  );

-- Profiles: sub_admin can list users (like educator/admin) for committee assignment
drop policy if exists "profiles_select_staff" on public.profiles;
create policy "profiles_select_staff"
  on public.profiles for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role in ('educator', 'admin', 'sub_admin')
    )
  );

grant select, insert, update, delete on all tables in schema public to postgres, service_role, authenticated;
