-- =============================================================================
-- 011: Course catalog import from CSV
-- =============================================================================

create table if not exists public.course_catalog (
  course_code text primary key,
  year_level int not null,
  course_title text not null,
  category text
);

insert into public.course_catalog (year_level, course_code, course_title, category) values
(1,'CHMD 1101','Thai Language and Communication','General Education'),
(1,'CHMD 1102','Mathematics and Physics for Health Science','General Education'),
(1,'CHMD 1103','Chemistry for Health Science','General Education'),
(1,'CHMD 1104','Introduction to Digital Technology','General Education'),
(1,'CHMD 1105','Introduction to Research','General Education'),
(1,'CHMD 1106','Biostatistics','General Education'),
(1,'CHMD 1107','Data Science and Health','General Education'),
(1,'CHMD 1108','Human Life','General Education'),
(1,'CHMD 1109','Doctor, Society and Social Responsibilities','General Education'),
(1,'CHMD 1110','Health System and Health Care Practice','General Education'),
(1,'CHMD 1111','Global Health and Disaster Medicine','General Education'),
(1,'CHMD 1112','One Health','General Education'),
(1,'CHMD 1113','Evidence-based Practice I','General Education'),
(1,'CHMD 1201','Cell Biology','Basic Sciences'),
(1,'CHMD 1202','Biochemistry and Molecular Biology','Basic Sciences'),
(1,'CHMD 1301','Infection and Defence','Medical Sciences'),
(2,'CHMD 2101','Academic English I','General Education'),
(2,'CHMD 2102','Academic English II','General Education'),
(2,'CHMD 2103','Physical Education (Circulation and Breathing)','General Education'),
(2,'CHMD 2301','Circulation and Breathing','Medical Sciences'),
(2,'CHMD 2302','Fluids, Nutrition and Metabolism','Medical Sciences'),
(2,'CHMD 2303','Endocrine System and Reproduction','Medical Sciences'),
(2,'CHMD 2304','Behavioural Sciences','Medical Sciences'),
(3,'CHMD 3101','Academic English III','General Education'),
(3,'CHMD 3102','Physical Education (Movement and Musculoskeletal Biology)','General Education'),
(3,'CHMD 3301','Movement and Musculoskeletal Biology','Medical Sciences'),
(3,'CHMD 3302','Mechanisms of Drug Action','Medical Sciences'),
(3,'CHMD 3303','Neuroscience and Behaviour','Medical Sciences'),
(3,'CHMD 3304','Development, Genetics and Cancer','Medical Sciences'),
(4,'CHMD 4501','Research and Innovation I','Research Practice'),
(4,'CHMD 4502','Research and Innovation II','Research Practice'),
(5,'CHMD 5101','Medical Profession I','General Education'),
(5,'CHMD 5102','Evidence-based Practice II','General Education'),
(5,'CHMD 5401','Ambulatory Care','Clinical Sciences and Practice'),
(5,'CHMD 5402','Internal Medicine I','Clinical Sciences and Practice'),
(5,'CHMD 5403','Family and Community Medicine','Clinical Sciences and Practice'),
(5,'CHMD 5404','General Surgery','Clinical Sciences and Practice'),
(5,'CHMD 5405','Trauma and Emergency Care','Clinical Sciences and Practice'),
(5,'CHMD 5406','Peri-operative Care','Clinical Sciences and Practice'),
(5,'CHMD 5407','Orthopaedics','Clinical Sciences and Practice'),
(5,'CHMD 5408','Rehabilitation and Palliative Care','Clinical Sciences and Practice'),
(6,'CHMD 6101','Medical Profession II','General Education'),
(6,'CHMD 6401','Obstetrics and Gynaecology','Clinical Sciences and Practice'),
(6,'CHMD 6402','Sexual Health and Genitourinary Medicine','Clinical Sciences and Practice'),
(6,'CHMD 6403','Geriatric Medicine','Clinical Sciences and Practice'),
(6,'CHMD 6404','Child and Adolescent Health','Clinical Sciences and Practice'),
(6,'CHMD 6405','Psychiatry','Clinical Sciences and Practice'),
(6,'CHMD 6406','Forensic Medicine','Clinical Sciences and Practice'),
(6,'CHMD 6407','Internal Medicine II','Clinical Sciences and Practice'),
(6,'CHMD 6408','Critical Care','Clinical Sciences and Practice'),
(6,'CHMD 6409','Interventional Radiology and Radiotherapy','Clinical Sciences and Practice'),
(6,'CHMD 6410','Surgical Specialties','Clinical Sciences and Practice'),
(6,'CHMD 6411','Otorhinolaryngology and Ophthalmology','Clinical Sciences and Practice'),
(7,'CHMD 7401','Externship in Family and Community Medicine','Clinical Sciences and Practice'),
(7,'CHMD 7402','Externship in Surgery, Orthopaedics and Emergency Care','Clinical Sciences and Practice'),
(7,'CHMD 7403','Externship in Internal Medicine and Ambulatory Care','Clinical Sciences and Practice'),
(7,'CHMD 7404','Externship in Paediatrics','Clinical Sciences and Practice'),
(7,'CHMD 7405','Externship in Obstetrics and Gynaecology','Clinical Sciences and Practice'),
(7,'CHMD 7601','Externship Elective I','Elective Courses'),
(7,'CHMD 7602','Externship Elective II','Elective Courses'),
(7,'CHMD 7603','Externship Elective III','Elective Courses'),
(7,'CHMD 7604','Externship Elective IV','Elective Courses'),
(7,'CHMD 7605','Research Elective I','Elective Courses'),
(7,'CHMD 7606','Research Elective II','Elective Courses')
on conflict (course_code) do update set
  year_level = excluded.year_level,
  course_title = excluded.course_title,
  category = excluded.category;

